language: objective-c
osx_image: xcode9.2
xcode_workspace: YandexMoneyCoreApi.xcworkspace
xcode_scheme: YandexMoneyCoreApiExamplePods
cache:
  bundler: true
  cocoapods: true
  directories:
  - Carthage
notifications:
  slack:
    secure: ATTEEGFApxA2TGYvRZqv5NLqNRvQGb2JNOsf+Hq4V9z2rS8YebjAYNurrDEPu4v9cBYyXJu+mTovycDX6EtlxT16dvc7SZip8pSzLSDdcbC8lPEPEY6MoZ/T+R7MzYVrLrunRCUXZRWMZZG59O+fXG6GsYMpt/ZQLMdK6pjCRkk4mM5LmOSU9rh9Zg06AR4dVn7Wf9OkQSeTrdw+W7UyxsIUby3u4Jyu0+pj+nccbZjBZ50AgegqBrgM4/G1q+5dn09gnLWgUjykv01oHR2S0DkENclga4pbW8Q/ZW83NE+ZE1zoUPyFiHpktF7oEXuZ9ToIbeAmqavyHMg1g0RXhYdAFfSwbSRpeWR6xdbgtgGHLGnKrYSZJZAidl3LGOu1hllraCDU8Asf5TR1214u3mpOYPuYr7pF09dHA6xAti3DhWKKNIf0GwzvlDC/TP16Hqhdjj6SmyrxrgO6noUd5+33ViO63bl5pRHFwn7D9zCNEg5Lj2BnGK4muagL0BUeonBdMP3dEMHYf7iHUlu2Of+z1kZO/XuIjIHrVuZOo2/5wFyl+kPFcu6Ll4d6ULhcTyw2bH6Ev6/NjFkHXyBsbsjbJ9iwvhp9OWDJQ7tZeXXt2uI9QS8zIHv2d6fxnvRGWmAmmUCh3P4T2gecwq67iRJ5WVCPHiFLVJiekKtFsWA=
before_install:
- brew update && brew bundle
- bundle install --jobs=3 --retry=3 --deployment
- pushd .
- bundle exec pod repo update
- bundle exec pod install
install: true
before_script:
- carthage bootstrap --platform iOS --cache-builds
script:
- swiftlint
- bundle exec fastlane build
- bundle exec fastlane scan
